some-info:
  description: Example of bug
  supported-clients: client1, client2
  clients:
    client1:
      some-number: 0.123
      some-string: TEXT
      some-custom-format:
        client1-params:
          operation-params:
            - codes: c1, c2, c3, c4
              responses:
                - type: typeA
                  response: "response A"
                - type: typeB
                  response: "response B"
                - type: typeC
                  response: "response C"
              default-response: "response D"
            - codes: c5
              response: "response E"
